### ISSUE TITLE
Large execution time for AIDM decoding

### ISSUE THREAD

**Issue by mpz** [asdf1011/libaisdec#2]
Seems AIDM decoding is spent much time. I captured data from device and AIDM stream is increase during encoding. Then encoding time is increase too because AIDM data was bigger. 

So with time decoding, need to spend more and more time. I have more than 1 GB memory on such process.

I use python lib for decoding.

Could you please help me with such issue?
Can i decrease execution time and memory for execution?

**Comment by asdf1011** [comment]
The decoding is pretty slow (running with pypy might help), but something is definitely going wrong if it's using that much memory. How big is the data you're trying to decode? There shouldn't be more than a single packet (made up of multiple fragments) in memory at a time.

**Comment by mpz** [comment]
Now i try to use pypy.

I have such data.

#### No pypy:

PACK 0. Ships: 1. Time elapsed: 5 sec
PACK 1. Ships: 18. Time elapsed: 4 sec
PACK 2. Ships: 25. Time elapsed: 7 sec
PACK 3. Ships: 36. Time elapsed: 6 sec
PACK 4. Ships: 49. Time elapsed: 9 sec
PACK 5. Ships: 79. Time elapsed: 10 sec
PACK 6. Ships: 94. Time elapsed: 13 sec
PACK 7. Ships: 108. Time elapsed: 30 sec
PACK 8. Ships: 255. Time elapsed: 19 sec
PACK 9. Ships: 202. Time elapsed: 17 sec
PACK 10. Ships: 208. Time elapsed: 24 sec
PACK 11. Ships: 225. Time elapsed: 26 sec
PACK 12. Ships: 248. Time elapsed: 33 sec
PACK 13. Ships: 303. Time elapsed: 25 sec
PACK 14. Ships: 297. Time elapsed: 34 sec
PACK 15. Ships: 321. Time elapsed: 25 sec

##### total ships: 2469, average decoding time: 8.6 ships/sec

#### data with pypy:

PACK 0. Ships: 8. Time elapsed: 12 sec
PACK 1. Ships: 67. Time elapsed: 15 sec
PACK 2. Ships: 114. Time elapsed: 16 sec
PACK 3. Ships: 55. Time elapsed: 16 sec
PACK 4. Ships: 106. Time elapsed: 17 sec
PACK 5. Ships: 90. Time elapsed: 16 sec
PACK 6. Ships: 121. Time elapsed: 15 sec
PACK 7. Ships: 145. Time elapsed: 17 sec
PACK 8. Ships: 146. Time elapsed: 15 sec
PACK 9. Ships: 124. Time elapsed: 16 sec
PACK 10. Ships: 133. Time elapsed: 15 sec
PACK 11. Ships: 109. Time elapsed: 15 sec
PACK 12. Ships: 127. Time elapsed: 16 sec
PACK 13. Ships: 94. Time elapsed: 15 sec
PACK 14. Ships: 109. Time elapsed: 16 sec
PACK 15. Ships: 69. Time elapsed: 15 sec
PACK 16. Ships: 2. Time elapsed: 6 sec

##### total ships: 1619, average decoding time: 6.4 ships/sec

Ships it is dynamic packet AIVDM. Static packets was also decoded

So seems i have increase decoding speed for 2 sec

Also i install NewRelic for monitoring.

**Comment by mpz** [comment]
Please close this issue. I find bug in my code. 
Thanks for pypy!

**Comment by asdf1011** [comment]
Great, glad you figured it out!
